export const OPEN_CART = "OPEN_CART";
export const CLOSE_CART = "CLOSE_CART";
export const CART_ADD_ITEM = "CART_ADD_ITEM";
export const CART_INCREMENT_ITEM = "CART_INCREMENT_ITEM";
export const CART_DECREMENT_ITEM = "CART_DECREMENT_ITEM";
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";
export const CART_SAVE_SHIPPING_ADDRESS = "CART_SAVE_SHIPPING_ADDRESS";
export const CLEAR_CART = "CLEAR_CART";
